// <auto-generated />
using System;
using DataCenter.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataCenter.Infrastructure.Migrations
{
    [DbContext(typeof(DataCenterDbContext))]
    [Migration("20260603141107_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataCenter.Domain.AggregatesModel.SSQHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("主键ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlueBall")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("蓝球号码");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("开奖日期");

                    b.Property<string>("OutBallOrder")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("出球顺序（按摇出顺序排列的号码）");

                    b.Property<string>("PeriodicalNO")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("开奖期号");

                    b.Property<string>("RedBalls")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("红球号码（逗号分隔，按大小顺序）");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime")
                        .HasDatabaseName("IX_SSQHistories_CreatedTime");

                    b.HasIndex("DrawDate")
                        .HasDatabaseName("IX_SSQHistories_DrawDate");

                    b.HasIndex("PeriodicalNO")
                        .IsUnique()
                        .HasDatabaseName("IX_SSQHistories_PeriodicalNO");

                    b.ToTable("SSQHistories", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
